server:
  port: 8070

spring:
  application:
    name: category-service
    
  data:
    mongodb:
     uri: mongodb://achraf:achraf@localhost:27017/category_db

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:6781/eureka
