spring:
  application:
    name: discovery

server:
  port: 6781

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:6781/eureka/
